AWSTemplateFormatVersion: "2010-09-09"
Description: |
  A bucket to store lambda function source codes.

Resources:
  LambdaCodeStoreBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: adben002-net-lambda-code-bucket

Outputs:
  BucketName:
    Value: !Ref LambdaCodeStoreBucket
    Description: Bucket name
    Export:
      Name: LambdaCodeBucket
