version: 0.2

phases:
  build:
    commands:
      - cd certificateValidator/
      - zip certificateValidator.zip *

artifacts:
  files:
    - certificateValidator/certificateValidator.zip
  discard-paths: yes
