AWSTemplateFormatVersion: "2010-09-09"
Description: |
  A bucket to store lambda function source codes.

Resources:
  LambdaCodeStoreBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  # Role for CodePipeline
  CodePipelineRoleqwq:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AccessPipelineBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: arn:aws:s3:::adben002-net-pipeline-test-init-codepipeline-artifact-store
              - Effect: Allow
                Action: s3:*
                Resource: arn:aws:s3:::adben002-net-pipeline-test-init-codepipeline-artifact-store/*
        - PolicyName: CloudformationPipelineDeployment
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/asdsadasdsad-codepipeline/*'
        - PolicyName: PassOntoSiteRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt SitePipeLineRoleasd.Arn

  SitePipeLineRoleasd:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [cloudformation.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/SystemAdministrator

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AccessPipelineBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: codebuild:StartBuild
                Resource: !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AWS::StackName}-LambdaBuilder'

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:latest
        Type: LINUX_CONTAINER
      Name: !Sub "${AWS::StackName}-LambdaBuilder"
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: ./app/lambda-buildspec.yaml

  # Pipeline for running source
  CodePipelineasdas:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: 'sadifojsaiodfjiosdjf-repo-codepipeline'
      RoleArn: !GetAtt CodePipelineRoleqwq.Arn
      ArtifactStore:
        Type: S3
        Location: adben002-net-pipeline-test-init-codepipeline-artifact-store
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                S3Bucket: adben002-net-pipeline-test-init-codepipeline-artifact-store
                S3ObjectKey: repo-source
              OutputArtifacts:
                - Name: RepoSourceasdasdas
              RunOrder: 1
        - Name: DeployLambda
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: RepoSourceasdasdas
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: sadsadsadsadsadsdretertr
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 1
            - Name: DeployPipeline
              InputArtifacts:
                - Name: sadsadsadsadsadsdretertr
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: 'asdsadasdsad-codepipeline'
                TemplatePath: RepoSourceasdasdas::lambda-bucket.yaml
                RoleArn: !GetAtt SitePipeLineRoleasd.Arn
              RunOrder: 2
