AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SourceStorageBucketName:
    Type: String
  DomainName:
    Type: String
    Description: The base domain name for the web site (no 'www')
    MinLength: 4
    MaxLength: 253
    AllowedPattern: '[a-z0-9]+[-.a-z0-9]*(\\.[a-z][a-z]+)+'
    ConstraintDescription: |
      Provide a valid domain name using only lowercase letters,
      numbers, ., and dash (-)

Resources:

  # Role for CodePipeline
  CodePipelineRoleqwq:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AccessPipelineBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${SourceStorageBucketName}'
              - Effect: Allow
                Action: s3:*
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${SourceStorageBucketName}/*'
        - PolicyName: CloudformationPipelineDeployment
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource: !Sub 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/asdsadasdsad-codepipeline/*'
        - PolicyName: RunBuild
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: !Sub 'arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AWS::StackName}-LambdaBuilder'
        - PolicyName: PassOntoSiteRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt SitePipeLineRoleasd.Arn
        - PolicyName: LambdaCodeBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: !Sub 'arn:${AWS::Partition}:s3:::adben002-net-lambda-code-bucket/*'

  SitePipeLineRoleasd:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [cloudformation.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/SystemAdministrator

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BuildLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-LambdaBuilder:log-stream:*'
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: AccessPipelineBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${SourceStorageBucketName}'
              - Effect: Allow
                Action: s3:*
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${SourceStorageBucketName}/*'

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
      Name: !Sub "${AWS::StackName}-LambdaBuilder"
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: ./lambda-buildspec.yaml

  SourceCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AccessSourceCodePipelineArtifactStore
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:putObject
                  - s3:getObject
                Resource: !Sub '${SourceCodePipelineArtifactStore.Arn}/*'

  SourceCodePipelineCloudformationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt SourceCodePipelineRole.Arn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SourceCodePipelineCloudformationDeploymentPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource: !Sub 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}-stack-pipeline/*'
        - PolicyName: SourceCodePipelineCloudformationPassOntoStackPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt StackDeploymentRole.Arn
        - PolicyName: AccessSourceCodePipelineArtifactStore
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:putObject
                  - s3:getObject
                Resource: !Sub '${SourceCodePipelineArtifactStore.Arn}/*'

  StackDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # Pipeline for running source
  CodePipelineasdas:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: 'sadifojsaiodfjiosdjf-repo-codepipeline'
      RoleArn: !GetAtt CodePipelineRoleqwq.Arn
      ArtifactStore:
        Type: S3
        Location: !Sub '${SourceStorageBucketName}'
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                S3Bucket: !Sub '${SourceStorageBucketName}'
                S3ObjectKey: source-code
              OutputArtifacts:
                - Name: RepoSourceasdasdas
              RunOrder: 1
        - Name: DeployLambda
          Actions:
            - Name: DeployPipeline
              InputArtifacts:
                - Name: RepoSourceasdasdas
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: 'asdsadasdsad-codepipeline'
                TemplatePath: RepoSourceasdasdas::lambda-bucket.yaml
                RoleArn: !GetAtt SitePipeLineRoleasd.Arn
              RunOrder: 1
            - Name: CodeBuild
              InputArtifacts:
                - Name: RepoSourceasdasdas
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: sadsadsadsadsadsdretertr
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 1
            - Name: CopyLambda
              InputArtifacts:
                - Name: sadsadsadsadsadsdretertr
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: adben002-net-lambda-code-bucket
                Extract: true
                ObjectKey: certificate-validator
              RunOrder: 2
            - Name: DeployStackPipeline
              InputArtifacts:
                - Name: RepoSourceasdasdas
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub '${AWS::StackName}-static-website'
                TemplatePath: RepoSourceCode::staticwebsite.yaml
                ParameterOverrides: !Join
                  - ''
                  - - '{'

                    - '"DomainName": "'
                    - !Ref DomainName
                    - '"'

                    - '}'
                RoleArn: !GetAtt StackDeploymentRole.Arn
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !GetAtt SourceCodePipelineCloudformationDeploymentRole.Arn
              RunOrder: 3
