AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GitHubOwner:
    Description: GitHub account username.
    Type: String
  GitHubRepo:
    Description: Static site repo name.
    Type: String
  GitHubBranch:
    Description: The branch that will trigger build/deploy.
    Type: String
    Default: master
  GitHubOAuthToken:
    Description: OAuth or personal access token.
    Type: String
    NoEcho: true

Resources:

  SourceCodePipelineArtifactStore:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  SourceStorage:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

  SourceCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole

  SourceCodePipelineCloudformationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt SourceCodePipelineRole.Arn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SourceCodePipelineCloudformationDeploymentPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource: !Sub 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}-stack-pipeline/*'
        - PolicyName: SourceCodePipelineCloudformationPassOntoStackPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt StackDeploymentRole.Arn

  AccessSourceCodePipelineArtifactStore:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AccessSourceCodePipelineArtifactStore
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:putObject
              - s3:getObject
            Resource: !Sub '${SourceCodePipelineArtifactStore.Arn}/*'
      Roles:
        - !Ref SourceCodePipelineRole
        - !Ref SourceCodePipelineCloudformationDeploymentRole

  StackDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  SourceCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt SourceCodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref SourceCodePipelineArtifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              OutputArtifacts:
                - Name: RepoSourceCode
        - Name: Deploy
          Actions:
            - Name: DeployStackPipeline
              InputArtifacts:
                - Name: RepoSourceCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub '${AWS::StackName}-stack-pipeline'
                TemplatePath: RepoSourceCode::pipeline.yaml
                ParameterOverrides: !Join
                  - ''
                  - - '{"SourceStorageBucketName": "'
                    - !Ref SourceStorage
                    - '"}'
                RoleArn: !GetAtt StackDeploymentRole.Arn
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !GetAtt SourceCodePipelineCloudformationDeploymentRole.Arn
              RunOrder: 1
            - Name: CopyRepoForStackPipeline
              InputArtifacts:
                - Name: RepoSourceCode
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: !Ref SourceStorage
                Extract: false
                ObjectKey: source-code
              RunOrder: 2
